// Package registry consumes the build-time snapshot of
// @gleanwork/mcp-config-schema (registry.json, generated by
// scripts/gen-registry.mjs) and produces per-client MCP server entries.
//
// The npm package is the source of truth; this package performs only
// placeholder substitution and exposes client metadata. No registry/builder
// logic is reimplemented beyond the well-defined server-name normalization.
package registry

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/gleanwork/glean-mdm/internal/platform"
)

//go:embed registry.json
var registryJSON []byte

// gleanPrefix mirrors the registry's server-name normalization: a name is
// prefixed with "glean_" unless it already begins with it.
const gleanPrefix = "glean_"

type snapshot struct {
	ServerNamePlaceholder string       `json:"serverNamePlaceholder"`
	ServerURLPlaceholder  string       `json:"serverUrlPlaceholder"`
	URLPropertyNames      []string     `json:"urlPropertyNames"`
	Clients               []*rawClient `json:"clients"`
}

type rawClient struct {
	ID                  string             `json:"id"`
	DisplayName         string             `json:"displayName"`
	ConfigFormat        string             `json:"configFormat"`
	ServersPropertyName string             `json:"serversPropertyName"`
	URLProperty         string             `json:"urlProperty"`
	ConfigPath          map[string]*string `json:"configPath"`
	EntryTemplate       map[string]any     `json:"entryTemplate"`
}

// Client describes a single MCP host application from the snapshot.
type Client struct {
	ID                  string
	DisplayName         string
	ConfigFormat        string
	ServersPropertyName string
	URLProperty         string

	configPath            map[string]*string
	entryTemplate         map[string]any
	serverNamePlaceholder string
	serverURLPlaceholder  string
}

var loaded *snapshot

func load() *snapshot {
	if loaded != nil {
		return loaded
	}
	var s snapshot
	if err := json.Unmarshal(registryJSON, &s); err != nil {
		panic(fmt.Sprintf("invalid embedded registry.json: %v", err))
	}
	loaded = &s
	return loaded
}

// Clients returns all clients in the snapshot.
func Clients() []*Client {
	s := load()
	out := make([]*Client, 0, len(s.Clients))
	for _, c := range s.Clients {
		out = append(out, &Client{
			ID:                    c.ID,
			DisplayName:           c.DisplayName,
			ConfigFormat:          c.ConfigFormat,
			ServersPropertyName:   c.ServersPropertyName,
			URLProperty:           c.URLProperty,
			configPath:            c.ConfigPath,
			entryTemplate:         c.EntryTemplate,
			serverNamePlaceholder: s.ServerNamePlaceholder,
			serverURLPlaceholder:  s.ServerURLPlaceholder,
		})
	}
	return out
}

// URLPropertyNames returns every URL property name used across all clients,
// mirroring getAllUrlPropertyNames in the original hosts/utils.ts.
func URLPropertyNames() []string {
	return append([]string(nil), load().URLPropertyNames...)
}

// NormalizeServerName applies the registry's "glean_" prefix rule.
func NormalizeServerName(name string) string {
	if strings.HasPrefix(name, gleanPrefix) {
		return name
	}
	return gleanPrefix + name
}

// ConfigPathFor returns the configured path for the given platform, and whether
// one exists for that platform.
func (c *Client) ConfigPathFor(p platform.Platform) (string, bool) {
	v, ok := c.configPath[string(p)]
	if !ok || v == nil || *v == "" {
		return "", false
	}
	return *v, true
}

// BuildEntry produces the server-entry value for this client, substituting the
// normalized server name and server URL into the captured template.
func (c *Client) BuildEntry(serverName, serverURL string) map[string]any {
	normalized := NormalizeServerName(serverName)
	substituted := substitute(c.entryTemplate, c.serverNamePlaceholder, normalized, c.serverURLPlaceholder, serverURL)
	m, _ := substituted.(map[string]any)
	return m
}

// substitute deep-copies value, replacing the name and URL placeholder tokens
// wherever they appear in string leaves.
func substitute(value any, namePlaceholder, name, urlPlaceholder, url string) any {
	switch v := value.(type) {
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, child := range v {
			out[k] = substitute(child, namePlaceholder, name, urlPlaceholder, url)
		}
		return out
	case []any:
		out := make([]any, len(v))
		for i, child := range v {
			out[i] = substitute(child, namePlaceholder, name, urlPlaceholder, url)
		}
		return out
	case string:
		v = strings.ReplaceAll(v, urlPlaceholder, url)
		v = strings.ReplaceAll(v, namePlaceholder, name)
		return v
	default:
		return v
	}
}
